import SideNav from "../../../../components/home/SideNav";
import { Metadata } from "next";

export const metadata = {
  title: "DX Studio",
  description: "Generated by Aliot DT",
};

export default function homeLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div
      style={{
        width: "119rem",
        height: "100%",
        display: "flex",
        overflowX: "hidden",
      }}
    >
      <SideNav />

      {children}
    </div>
  );
}
